export { ReactComponent as IconButtonLeft } from './arrow-left.react.svg';
export { ReactComponent as BlockPopupIcon } from './block-popup.react.svg';
export { ReactComponent as CheckPopupIcon } from './check-popup.react.svg';
export { ReactComponent as emptyDataIcon } from './empty-ilustration.react.svg';
export { ReactComponent as FilterIcon } from './filter.react.svg';
export { ReactComponent as LockIcon } from './lock.react.svg';
export { ReactComponent as noDataIcon } from './no-data.react.svg';
export { ReactComponent as PenIcon } from './pen.react.svg';
export { ReactComponent as UserIcon } from './user.react.svg';
