apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'atomaks-6778'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 'atomaks-6778'
  template:
    metadata:
      labels:
        app: 'atomaks-6778'
    spec:
      containers:
        - name: 'atomaks-6778'
          image: 'atomfrontcr.azurecr.io/atomaks'
          ports:
            - containerPort: 6005
